### ISSUE TITLE
No SSL support?

### ISSUE THREAD

**Issue by deg0nz** [vinaychandra/Moodle-Downloader#2]
I'm wondering if your moodle installaton has no SSL support. Which is quite weird because sending your credentials via internet without SSL is a bad idea.

The moodle site of my High School supports SSL only.

After a little research, it seems, that [urllib2 does not support SSL ](https://github.com/wbond/package_control/issues/557)and causes the following error:

```
% python2 moodle.py                                                                                                                                                   Password:
Traceback (most recent call last):
  File "moodle.py", line 47, in <module>
    response = urllib2.urlopen(req)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 454, in _open
    'unknown_open', req)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1265, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib2.URLError: <urlopen error unknown url type: "https>
exit: 1
```

I'm not very familiar with python, so do you have any idea to fix this without much pain?

**Comment by vinaychandra** [comment]
I think you also need a python installation http://stackoverflow.com/a/2146467 supporting that. Please note that even if you do have an installation, this downloader might not work with your moodle specifically. This is originally intended for IIT Bombay but may work on others.

**Comment by deg0nz** [comment]
Ok, thanks.
I'll try to modify the script to work with the moodle here... If I succeed, I'll tell you and upload the script.
